### ISSUE TITLE
[DOC] Readme.md

### ISSUE THREAD

**Issue by riyenas0925** [osamhack2020/WEB_KookMoBan_PonJohmNaimann#110]
<p align="center">
<img alt="GitHub contributors" src="https://user-images.githubusercontent.com/32615702/97505907-21b5ad80-19bd-11eb-9d03-4959b24b4375.png" width="50%">
</p>

## 분야별 저장소

<p align="center">
  <img src="https://img.shields.io/badge/WEB_Repository-black?&style=flat">
  <img src="https://github.com/osamhack2020/WEB_KookMoBan_PonJohmNaimann/workflows/Java%20CI%20with%20Gradle/badge.svg?branch=develop"> 
  <img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/WEB_KookMoBan_PonJohmNaimann"> 
  <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/WEB_KookMoBan_PonJohmNaimann"> 
  <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/WEB_KookMoBan_PonJohmNaimann">
</p>
<p align="center">
  <img src="https://img.shields.io/badge/IoT_Repository-black?&style=flat">
  <img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/IoT_KookMoBan_PonJohmNaimann"> 
  <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/IoT_KookMoBan_PonJohmNaimann"> 
  <img src="https://img.shields.io/badge/Arduino_Code_License-GPL 3.0-green?&style=flat">
  <img src="https://img.shields.io/badge/RaspberryPi_Code_License-BSD--3--Clause-green?&style=flat">
</p>
<p align="center">
  <img src="https://img.shields.io/badge/APP_Repository-black?&style=flat">
  <img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/APP_KookMoBanUser_PonJohmNaimann"> 
  <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/APP_KookMoBanUser_PonJohmNaimann"> 
  <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/APP_KookMoBanUser_PonJohmNaimann">
</p>

## 팀소개
'폰 좀 내이만(Pon Johm Naimann)' 팀은 생활관 병사 스마트폰 비대면 반납 시스템 개발을 목표로 '국방모바일반납' 프로젝트를 진행하고 있습니다.

본 프로젝트는 IoT, APP, WEB 기술을 모두 결합함으로써, 간편하고 체계적인 반납 시스템을 구축하면서도 그 속에서 병사가 느끼는 부담을 최소화하는 것을 목적으로 개발을 진행하고 있습니다.

본 프로젝트는 오픈소스 프로젝트로 진행되며, 본 프로젝트에 관심이 있는 개발자, 사용자들을 위해 튜토리얼 GitBook을 제작하여 공개하고 있습니다.

<p align="center">
<a href="https://kookmoban.gitbook.io/osam/">
<img src="https://img.shields.io/badge/GitBook-project_doc-blue?&style=for-the-badge&logo=github">
</a>
    
<a href="https://www.notion.so/OSAM-265735b9b76b4bccbff7ce2c4739acd9"  target="_blank">
<img src="https://img.shields.io/badge/NOTION-team_page-green?&style=for-the-badge&logo=notion">
</a>

<a href="https://osam.riyenas.dev/swagger-ui.html">
<img src="https://img.shields.io/badge/Swagger-API_Doc-yellow?&style=for-the-badge&logo=swagger">
</a>

<a href="https://osam.riyenas.dev">
<img src="https://img.shields.io/badge/WebSite-Live--Demo-blueviolet?&style=for-the-badge&logo=google">
</a>
</p>

## 프로젝트 설명 동영상

<p align="center">
<a href="https://youtu.be/bAUkok-NNVs"  target="_blank">
<img src="http://img.youtube.com/vi/bAUkok-NNVs/0.jpg">
</a>
</p>

### IoT 반납기
QR코드 인식, 무게 감지, 문 잠금, 서버와의 통신 등의 기능이 탑재되어 있습니다. 기기에서 반납 APP을 켜고 반납기에 넣으면 자동으로 QR코드를 감지하고 반납 기록을 서버에 전송합니다.

<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/32615702/97666855-dcc76f00-1ac1-11eb-9202-53da0c877559.jpg"></td>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97667117-80188400-1ac2-11eb-981d-9602fe2241c1.jpg"></td>
    <td><img src="https://user-images.githubusercontent.com/32615702/97666861-de913280-1ac1-11eb-958f-0a2885af5b6c.jpg"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97554903-ca462a80-1a1a-11eb-888d-04530340a13f.GIF"></td>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97554899-c914fd80-1a1a-11eb-9a2b-e5334d59531e.GIF"></td>
  </tr>
<tr>
</table>

### APP
초기 등록시에 서버와 통신하여 기기를 등록한 뒤, 이후에는 Time-based OTP기술을 활용해 기기 고유의 QR코드를 출력합니다. 이 앱은 어떠한 권한도 요구하지 않습니다.
  
<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/32615702/97541954-52bbcf80-1a09-11eb-876a-c20fcffd9d6d.jpg"></td>
    <td><img src="https://user-images.githubusercontent.com/32615702/97541958-53ecfc80-1a09-11eb-8928-f6b93888bbfe.jpg"></td>
    <td><img src="https://user-images.githubusercontent.com/32615702/97541959-53ecfc80-1a09-11eb-8e0f-664dbc2870a0.jpg"></td>
<tr>
</table>

### WEB(Back-End API Server)
기기 관리자 현황, 등록 기기 현황, 기기 반납 현황을 관리하는 서버입니다. 각종 API를 지원하며, 주로 POST와 GET을 통해 요청을 받습니다.

<p align="center">
  <a href="https://osam.riyenas.dev/swagger-ui.html">
    <img src="https://img.shields.io/badge/Swagger-API_Doc-yellow?&style=for-the-badge&logo=swagger">
  </a>
</p>

### WEB(Front-End)
Argon Dashboard를 관리자용 페이지를 제작하였으며, 간편하게 반납 정보 조회 및 관리를 할 수 있도록 제작되었습니다.

<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/32615702/97557804-9cfb7b80-1a1e-11eb-97f7-29803bd21e79.png"></td>
    <td><img src="https://user-images.githubusercontent.com/32615702/97557809-9ec53f00-1a1e-11eb-982a-2ae13bdc3299.png"></td>
  </tr>
</table>

## 컴퓨터 구성 / 필수 조건 안내 (Prerequisites)

- IoT 반납기: 라즈베리파이 3B,B+, 4B 사용, 아두이노 나노 V3
- App: 안드로이드 00이상
- WEB:

## 기술 스택 (Technique Used)

- IoT 사용 라이브러리
    - pyzbar (MIT)
    - pillow (HPND)
    - opencv-python (MIT)
    - picamera (BSD)
    - serial (MIT)
    - numpy (BSD)
    - pybase64 (BSD)
- APP
    - 
- WEB
    - 

## 설치 안내 (Installation Process)

자세한 빌드 방법은 아래 튜토리얼 페이지를 참고하십시오.

<p align="center">
  <a href="https://kookmoban.gitbook.io/osam/how-to-build/undefined-5">
    <img src="https://img.shields.io/badge/GitBook-HOW_TO_BUILD-blue?&style=for-the-badge&logo=github">
  </a>
</p>

## 프로젝트 사용법 (Getting Started)

자세한 사용 방법은 아래 튜토리얼 페이지를 참고하십시오.

<p align="center">
  <a href="https://kookmoban.gitbook.io/osam/how-to-use/undefined-4">
    <img src="https://img.shields.io/badge/GitBook-HOW_TO_USE-blue?&style=for-the-badge&logo=github">
  </a>
</p>

## 팀 정보 (Team Information)
- park chan jeong ([ckswjd99@gmail.com](mailto:ckswjd99@gmail.com)), Github Id: ckswjd99
- kang dong min ([riyenas0925@gmail.com](mailto:riyenas0925@gmail.com)), Github Id: riyenas0925
- lee jin whuy ([jinwhuy.lee@gmail.com](mailto:jinwhuy.lee@gmail.com)), Github Id: jinwhuy

## 저작권 및 사용권 정보 (Copyleft / End User License)
<p align="center">
  <img src="http://www.cckorea.org/images/ccl/lic_by_sa_g.gif"/>
</p>
Pon Johm Naimann에 의해 창작된 본 저장소의 모든 내용들은 크리에이티브 커먼즈 [저작자표시-동일조건변경허락 4.0 국제 (CC BY-SA 4.0)]에 따라 이용할 수 있습니다.

**Comment by riyenas0925** [comment]
![logo](https://user-images.githubusercontent.com/32615702/97505907-21b5ad80-19bd-11eb-9d03-4959b24b4375.png)

**Comment by riyenas0925** [comment]
<a href="https://www.buymeacoffee.com/roniemartinez" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/default-orange.png" alt="Buy Me A Coffee" height="41" width="174"></a>

**Comment by riyenas0925** [comment]
![IMG_0441](https://user-images.githubusercontent.com/32615702/97541954-52bbcf80-1a09-11eb-876a-c20fcffd9d6d.jpg)
![IMG_0443](https://user-images.githubusercontent.com/32615702/97541958-53ecfc80-1a09-11eb-8928-f6b93888bbfe.jpg)
![IMG_0444](https://user-images.githubusercontent.com/32615702/97541959-53ecfc80-1a09-11eb-8e0f-664dbc2870a0.jpg)

**Comment by riyenas0925** [comment]
![IMG_0455](https://user-images.githubusercontent.com/32615702/97544404-e5aa3900-1a0c-11eb-8f1c-da8d350a1347.jpg)

![06](https://user-images.githubusercontent.com/32615702/97544360-d32fff80-1a0c-11eb-9971-6305280f70b0.png)

**Comment by riyenas0925** [comment]
![whole](https://user-images.githubusercontent.com/32615702/97554899-c914fd80-1a1a-11eb-9a2b-e5334d59531e.GIF)
![test](https://user-images.githubusercontent.com/32615702/97554903-ca462a80-1a1a-11eb-888d-04530340a13f.GIF)

**Comment by riyenas0925** [comment]
![png](https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png)

**Comment by riyenas0925** [comment]
![Untitled (1)](https://user-images.githubusercontent.com/32615702/97557804-9cfb7b80-1a1e-11eb-97f7-29803bd21e79.png)
![Untitled](https://user-images.githubusercontent.com/32615702/97557809-9ec53f00-1a1e-11eb-982a-2ae13bdc3299.png)

**Comment by riyenas0925** [comment]
# Introduction
<p align="center">
<img alt="GitHub contributors" src="https://user-images.githubusercontent.com/32615702/97505907-21b5ad80-19bd-11eb-9d03-4959b24b4375.png" width="50%">
</p>

**국방모바일보안**은 병사와 통제간부 모두가 만족하며 사용할 수 있는, **일방적인 금지와 통제**로 이루어지지 않는 스마트폰 반납 시스템을 개발하기 위한 프로젝트입니다. IoT, APP, WEB 분야의 기술을 함께 사용합니다.

# Manual
본 프로젝트는 오픈소스 프로젝트로 진행되며, 본 프로젝트에 관심이 있는 개발자와 사용자를 위하여 **튜토리얼 GitBook**을 제작하여 공개하고 있습니다.

<p align="center">
<a href="https://kookmoban.gitbook.io/osam/">
<img src="https://img.shields.io/badge/GitBook-project_doc-blue?&style=for-the-badge&logo=github">
</a>
</p>


# Contribution
금년도 오픈소스아카데미 집체교육이 **비대면**으로 이루어짐에 따라, 모든 프로젝트는 **서로 얼굴도 알지 못하는 상태**에서 진행됩니다. 따라서 소통은 실시간 소통이 가능하고 문서화에 유리한 아래의 **Notion 페이지**에서 이루어집니다.

<p align="center">
<a href="https://www.notion.so/OSAM-265735b9b76b4bccbff7ce2c4739acd9"  target="_blank">
<img src="https://img.shields.io/badge/NOTION-team_page-green?&style=for-the-badge&logo=notion">
</a>
</p>


# License
라이센스의 구체적인 내용 및 써드파티 SW에 대해서는 본 리포지토리의 LICENSE 파일 및 튜토리얼 GitBook의 <a href="https://kookmoban.gitbook.io/osam/license/web">LICENSE 페이지</a>를 참조하십시오.
* IoT
  * Code for Arduino: GPLv3.0
  * Code for RaspberryPi: BSD-3
* APP: BSD-3
* WEB: BSD-3



# Copyright
<p align="center">
<img src="http://www.cckorea.org/images/ccl/lic_by_sa_g.gif"/>
</p>
Pon Johm Naimann에 의해 창작된 본 저장소의 모든 내용들은 크리에이티브 커먼즈 [저작자표시-동일조건변경허락 4.0 국제 (CC BY-SA 4.0)]에 따라 이용할 수 있습니다.

**Comment by ckswjd99** [comment]
<p align="center">
<img alt="GitHub contributors" src="https://user-images.githubusercontent.com/32615702/97505907-21b5ad80-19bd-11eb-9d03-4959b24b4375.png" width="50%">
</p>


<h5 align="left">WEB Repository</h5>

<img src="https://github.com/osamhack2020/WEB_KookMoBan_PonJohmNaimann/workflows/Java%20CI%20with%20Gradle/badge.svg?branch=develop"> <img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/WEB_KookMoBan_PonJohmNaimann"> <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/WEB_KookMoBan_PonJohmNaimann"> <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/WEB_KookMoBan_PonJohmNaimann">

<h5 align="left">IoT Repository</h5>

<img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/IoT_KookMoBan_PonJohmNaimann"> <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/IoT_KookMoBan_PonJohmNaimann"> <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/IoT_KookMoBan_PonJohmNaimann">

<h5 align="left">App Repository</h5>

<img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/APP_KookMoBanUser_PonJohmNaimann"> <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/APP_KookMoBanUser_PonJohmNaimann"> <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/APP_KookMoBanUser_PonJohmNaimann">

## 팀소개
'폰 좀 내이만(Pon Johm Naimann)' 팀은 생활관 병사 스마트폰 비대면 반납 시스템 개발을 목표로 '국방모바일반납' 프로젝트를 진행하고 있습니다.

본 프로젝트는 IoT, APP, WEB 기술을 모두 결합함으로써, 간편하고 체계적인 반납 시스템을 구축하면서도 그 속에서 병사가 느끼는 부담을 최소화하는 것을 목적으로 개발을 진행하고 있습니다.

본 프로젝트는 오픈소스 프로젝트로 진행되며, 본 프로젝트에 관심이 있는 개발자, 사용자들을 위해 튜토리얼 GitBook을 제작하여 공개하고 있습니다.

<p align="center">
<a href="https://kookmoban.gitbook.io/osam/">
<img src="https://img.shields.io/badge/GitBook-project_doc-blue?&style=for-the-badge&logo=github">
</a>
    
<a href="https://www.notion.so/OSAM-265735b9b76b4bccbff7ce2c4739acd9"  target="_blank">
<img src="https://img.shields.io/badge/NOTION-team_page-green?&style=for-the-badge&logo=notion">
</a>

<a href="https://osam.riyenas.dev/swagger-ui.html">
<img src="https://img.shields.io/badge/Swagger-API_Doc-yellow?&style=for-the-badge&logo=swagger">
</a>

<a href="https://osam.riyenas.dev">
<img src="https://img.shields.io/badge/WebSite-Live--Demo-blueviolet?&style=for-the-badge&logo=google">
</a>
</p>

## 프로젝트 설명 동영상

<p align="center">
<a href="https://youtu.be/BGCf6UDqF24"  target="_blank">
<img src="http://img.youtube.com/vi/vE43qMqlVfU/0.jpg">
</a>
</p>

## 기능 설계

### IoT 반납기
QR코드 인식, 무게 감지, 문 잠금, 서버와의 통신 등의 기능이 탑재되어 있습니다. 기기에서 반납 APP을 켜고 반납기에 넣으면 자동으로 QR코드를 감지하고 반납 기록을 서버에 전송합니다.
<table>
      <tr>
    <td><img src="https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png"></td>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png"></td>
    <td><img src="https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97554903-ca462a80-1a1a-11eb-888d-04530340a13f.GIF"></td>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97554899-c914fd80-1a1a-11eb-9a2b-e5334d59531e.GIF"></td>
  </tr>
<tr>
</table>

### APP
초기 등록시에 서버와 통신하여 기기를 등록한 뒤, 이후에는 Time-based OTP기술을 활용해 기기 고유의 QR코드를 출력합니다. 이 앱은 어떠한 권한도 요구하지 않습니다.


<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/32615702/97541954-52bbcf80-1a09-11eb-876a-c20fcffd9d6d.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/32615702/97541958-53ecfc80-1a09-11eb-8928-f6b93888bbfe.jpg"></td>￼ 
<td><img src="https://user-images.githubusercontent.com/32615702/97541959-53ecfc80-1a09-11eb-8e0f-664dbc2870a0.jpg"></td>
</tr>
</table>

### WEB(Back-End API Server)
기기 관리자 현황, 등록 기기 현황, 기기 반납 현황을 관리하는 서버입니다. 각종 API를 지원하며, 주로 POST와 GET을 통해 요청을 받습니다.

<p align="center">
<a href="https://osam.riyenas.dev/swagger-ui.html">
<img src="https://img.shields.io/badge/Swagger-API_Doc-yellow?&style=for-the-badge&logo=swagger">
</a>
</p>

### WEB(Front-End)
Argon Dashboard를 관리자용 페이지를 제작하였으며, 간편하게 반납 정보 조회 및 관리를 할 수 있도록 제작되었습니다.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/32615702/97557804-9cfb7b80-1a1e-11eb-97f7-29803bd21e79.png"></td>
<td><img src="https://user-images.githubusercontent.com/32615702/97557809-9ec53f00-1a1e-11eb-982a-2ae13bdc3299.png"></td>
</tr>
</table>

## 컴퓨터 구성 / 필수 조건 안내 (Prerequisites)

- IoT 반납기: 라즈베리파이 3B,B+, 4B 사용, 아두이노 나노 V3
- App: 안드로이드 00이상
- WEB:

## 기술 스택 (Technique Used)

- IoT 사용 라이브러리
    - pyzbar (MIT)
    - pillow (HPND)
    - opencv-python (MIT)
    - picamera (BSD)
    - serial (MIT)
    - numpy (BSD)
    - pybase64 (BSD)
- APP
    - 
- WEB
    - 

## 설치 안내 (Installation Process)

자세한 빌드 방법은 아래 튜토리얼 페이지를 참고하십시오.

[시스템 구성](https://kookmoban.gitbook.io/osam/how-to-build/undefined-5)

## 프로젝트 사용법 (Getting Started)

자세한 사용 방법은 아래 튜토리얼 페이지를 참고하십시오.

[관리자 설정](https://kookmoban.gitbook.io/osam/how-to-use/undefined-4)

## 팀 정보 (Team Information)

- park chan jeong ([ckswjd99@gmail.com](mailto:ckswjd99@gmail.com)), Github Id: ckswjd99
- kang dong min ([riyenas0925@gmail.com](mailto:riyenas0925@gmail.com)), Github Id: riyenas0925
- lee jin whuy ([jinwhuy.lee@gmail.com](mailto:jinwhuy.lee@gmail.com)), Github Id: jinwhuy

## 저작권 및 사용권 정보 (Copyleft / End User License)
<p align="center">
<img src="http://www.cckorea.org/images/ccl/lic_by_sa_g.gif"/>
</p>
Pon Johm Naimann에 의해 창작된 본 저장소의 모든 내용들은 크리에이티브 커먼즈 [저작자표시-동일조건변경허락 4.0 국제 (CC BY-SA 4.0)]에 따라 이용할 수 있습니다.

**Comment by riyenas0925** [comment]
<p align="center">
<img alt="GitHub contributors" src="https://user-images.githubusercontent.com/32615702/97505907-21b5ad80-19bd-11eb-9d03-4959b24b4375.png" width="50%">
</p>


<h5 align="left">WEB Repository</h5>

<img src="https://github.com/osamhack2020/WEB_KookMoBan_PonJohmNaimann/workflows/Java%20CI%20with%20Gradle/badge.svg?branch=develop"> <img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/WEB_KookMoBan_PonJohmNaimann"> <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/WEB_KookMoBan_PonJohmNaimann"> <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/WEB_KookMoBan_PonJohmNaimann">

<h5 align="left">IoT Repository</h5>

<img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/IoT_KookMoBan_PonJohmNaimann"> <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/IoT_KookMoBan_PonJohmNaimann"> <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/IoT_KookMoBan_PonJohmNaimann">

<h5 align="left">App Repository</h5>

<img alt="GitHub closed issues" src="https://img.shields.io/github/issues-closed/osamhack2020/APP_KookMoBanUser_PonJohmNaimann"> <img alt="GitHub closed pull requests" src="https://img.shields.io/github/issues-pr-closed/osamhack2020/APP_KookMoBanUser_PonJohmNaimann"> <img alt="GitHub" src="https://img.shields.io/github/license/osamhack2020/APP_KookMoBanUser_PonJohmNaimann">

## 팀소개
'폰 좀 내이만(Pon Johm Naimann)' 팀은 생활관 병사 스마트폰 비대면 반납 시스템 개발을 목표로 '국방모바일반납' 프로젝트를 진행하고 있습니다.

본 프로젝트는 IoT, APP, WEB 기술을 모두 결합함으로써, 간편하고 체계적인 반납 시스템을 구축하면서도 그 속에서 병사가 느끼는 부담을 최소화하는 것을 목적으로 개발을 진행하고 있습니다.

본 프로젝트는 오픈소스 프로젝트로 진행되며, 본 프로젝트에 관심이 있는 개발자, 사용자들을 위해 튜토리얼 GitBook을 제작하여 공개하고 있습니다.

<p align="center">
<a href="https://kookmoban.gitbook.io/osam/">
<img src="https://img.shields.io/badge/GitBook-project_doc-blue?&style=for-the-badge&logo=github">
</a>
    
<a href="https://www.notion.so/OSAM-265735b9b76b4bccbff7ce2c4739acd9"  target="_blank">
<img src="https://img.shields.io/badge/NOTION-team_page-green?&style=for-the-badge&logo=notion">
</a>

<a href="https://osam.riyenas.dev/swagger-ui.html">
<img src="https://img.shields.io/badge/Swagger-API_Doc-yellow?&style=for-the-badge&logo=swagger">
</a>

<a href="https://osam.riyenas.dev">
<img src="https://img.shields.io/badge/WebSite-Live--Demo-blueviolet?&style=for-the-badge&logo=google">
</a>
</p>

## 프로젝트 설명 동영상

<p align="center">
<a href="https://youtu.be/BGCf6UDqF24"  target="_blank">
<img src="http://img.youtube.com/vi/vE43qMqlVfU/0.jpg">
</a>
</p>

## 기능 설계

### IoT 반납기
QR코드 인식, 무게 감지, 문 잠금, 서버와의 통신 등의 기능이 탑재되어 있습니다. 기기에서 반납 APP을 켜고 반납기에 넣으면 자동으로 QR코드를 감지하고 반납 기록을 서버에 전송합니다.
<table>
      <tr>
    <td><img src="https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png"></td>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png"></td>
    <td><img src="https://user-images.githubusercontent.com/32615702/97555214-2e68ee80-1a1b-11eb-8f17-f92282fab0c6.png"></td>
  </tr>
  <tr>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97554903-ca462a80-1a1a-11eb-888d-04530340a13f.GIF"></td>
    <td colspan="2"><img src="https://user-images.githubusercontent.com/32615702/97554899-c914fd80-1a1a-11eb-9a2b-e5334d59531e.GIF"></td>
  </tr>
<tr>
</table>

### APP
초기 등록시에 서버와 통신하여 기기를 등록한 뒤, 이후에는 Time-based OTP기술을 활용해 기기 고유의 QR코드를 출력합니다. 이 앱은 어떠한 권한도 요구하지 않습니다.


<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/32615702/97541954-52bbcf80-1a09-11eb-876a-c20fcffd9d6d.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/32615702/97541958-53ecfc80-1a09-11eb-8928-f6b93888bbfe.jpg"></td>￼ 
<td><img src="https://user-images.githubusercontent.com/32615702/97541959-53ecfc80-1a09-11eb-8e0f-664dbc2870a0.jpg"></td>
</tr>
</table>

### WEB(Back-End API Server)
기기 관리자 현황, 등록 기기 현황, 기기 반납 현황을 관리하는 서버입니다. 각종 API를 지원하며, 주로 POST와 GET을 통해 요청을 받습니다.

<p align="center">
<a href="https://osam.riyenas.dev/swagger-ui.html">
<img src="https://img.shields.io/badge/Swagger-API_Doc-yellow?&style=for-the-badge&logo=swagger">
</a>
</p>

### WEB(Front-End)
Argon Dashboard를 관리자용 페이지를 제작하였으며, 간편하게 반납 정보 조회 및 관리를 할 수 있도록 제작되었습니다.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/32615702/97557804-9cfb7b80-1a1e-11eb-97f7-29803bd21e79.png"></td>
<td><img src="https://user-images.githubusercontent.com/32615702/97557809-9ec53f00-1a1e-11eb-982a-2ae13bdc3299.png"></td>
</tr>
</table>

## 컴퓨터 구성 / 필수 조건 안내 (Prerequisites)

- IoT 반납기: 라즈베리파이 3B,B+, 4B 사용, 아두이노 나노 V3
- App: 안드로이드 00이상
- WEB:

## 기술 스택 (Technique Used)

- IoT 사용 라이브러리
    - pyzbar (MIT)
    - pillow (HPND)
    - opencv-python (MIT)
    - picamera (BSD)
    - serial (MIT)
    - numpy (BSD)
    - pybase64 (BSD)
- APP
    - 
- WEB
    - 

## 설치 안내 (Installation Process)

자세한 빌드 방법은 아래 튜토리얼 페이지를 참고하십시오.

[시스템 구성](https://kookmoban.gitbook.io/osam/how-to-build/undefined-5)

## 프로젝트 사용법 (Getting Started)

자세한 사용 방법은 아래 튜토리얼 페이지를 참고하십시오.

[관리자 설정](https://kookmoban.gitbook.io/osam/how-to-use/undefined-4)

## 팀 정보 (Team Information)

- park chan jeong ([ckswjd99@gmail.com](mailto:ckswjd99@gmail.com)), Github Id: ckswjd99
- kang dong min ([riyenas0925@gmail.com](mailto:riyenas0925@gmail.com)), Github Id: riyenas0925
- lee jin whuy ([jinwhuy.lee@gmail.com](mailto:jinwhuy.lee@gmail.com)), Github Id: jinwhuy

## 저작권 및 사용권 정보 (Copyleft / End User License)
<p align="center">
<img src="http://www.cckorea.org/images/ccl/lic_by_sa_g.gif"/>
</p>
Pon Johm Naimann에 의해 창작된 본 저장소의 모든 내용들은 크리에이티브 커먼즈 [저작자표시-동일조건변경허락 4.0 국제 (CC BY-SA 4.0)]에 따라 이용할 수 있습니다.

**Comment by riyenas0925** [comment]
![IMG_0458](https://user-images.githubusercontent.com/32615702/97666705-8c501180-1ac1-11eb-9c90-2c02f47e5a90.jpg)
![IMG_0461](https://user-images.githubusercontent.com/32615702/97666709-8e19d500-1ac1-11eb-9f6d-346ede925ffc.jpg)

**Comment by riyenas0925** [comment]
![IMG_0458](https://user-images.githubusercontent.com/32615702/97666855-dcc76f00-1ac1-11eb-9202-53da0c877559.jpg)
![IMG_0461](https://user-images.githubusercontent.com/32615702/97666861-de913280-1ac1-11eb-958f-0a2885af5b6c.jpg)
![IMG_0459](https://user-images.githubusercontent.com/32615702/97667117-80188400-1ac2-11eb-981d-9602fe2241c1.jpg)
