### ISSUE TITLE
[ENH] 앱에서 병사정보를 받아 DB에 저장 기능 구현

### ISSUE THREAD

**Issue by riyenas0925** [osamhack2020/WEB_KookMoBan_PonJohmNaimann#14]
* Rest API로 구성
* POST방식으로 앱에서 보내줌
* 반환값으로 UUID값을 반환
* 앱에서 보내주는 정보는 아래와 같이 구성

```
//requset
{
    "name" : "홍길동",
    "rank" : "병장",
    "unit" : "국방부 국직부대 정보체계개발단",
    "serialNumber" : "S/NSDF65SF45S4F52FD3AS3DF",
    "type" : "tablet",
    "manufacturer" : "삼성",
    "phoneNumber" : "010-1234-5678"
}
```

**Comment by riyenas0925** [comment]
@Jinwhuy 진휘님 회원가입 성공시 UUID값을 반환해주려고 하는데 혹시 사용자정보나, 핸드폰 정보도 같이 넘겨주면 편한가요?
여기서 UUID값은 나중에 otp 생성때 사용할 seed값입니다!

**Comment by Jinwhuy** [comment]
> @Jinwhuy 진휘님 회원가입 성공시 UUID값을 반환해주려고 하는데 혹시 사용자정보나, 핸드폰 정보도 같이 넘겨주면 편한가요?
> 여기서 UUID값은 나중에 otp 생성때 사용할 seed값입니다!

@riyenas0925  UUID값만 반환해주셔도 될 것 같습니다~
