### ISSUE TITLE
[ENH] 반납기로부터 반납 기록을 받아 기록하는 기능 구현

### ISSUE THREAD

**Issue by ckswjd99** [osamhack2020/WEB_KookMoBan_PonJohmNaimann#43]
라즈베리파이로 구성된 반납기로부터 아래와 같은 정보를 POST요청을 통해 받는다.
```
{
      deviceId : 기기 ID,
      returnTime : 기기가 반납된 시간,
      weight : 반납 시점에 측정된 기기의 무게,
      photo : 반납 시점의 핸드폰 사진 (Base64로 Encoding됨)
}
```

서버에서는 이를 바탕으로 반납 기록을 추가하고, 특이사항 여부를 점검한다.

응답으로는 반납 기록 추가가 성공했는지 여부를 전송한다.

**Comment by riyenas0925** [comment]
~~@ckswjd99 찬정님 이미지를 DB에 직접적으로 저장하면 병목이 생겨서 성능상 문제가 많다고 하네요...~~

생각해보니까 Base64로 받고 서버단에서 파일로 저장하면 될것 같습니다ㅋㅋ

**Comment by ckswjd99** [comment]
returnTime의 경우 날짜를 밀리초 단위로 변환하여 보낸다.
photo의 경우 jpeg타입의 이미지를 base64로 변환하여 보낸다.
