### ISSUE TITLE
[ENH] 병사 등록시 계급(Rank), 부대(Unit) 정보 제거

### ISSUE THREAD

**Issue by Jinwhuy** [osamhack2020/WEB_KookMoBan_PonJohmNaimann#57]
serviceNumber, signUpCode 도입으로 더이상 기존의 rank와 unit key가 필요하지 않아서 이슈 남겼습니다, ~~또 관리자 앱에서 병사들의 반납 현황을 파악할 때 반납여부정보가 필요해서요. json에 return 키 추가 부탁드립니다.~~

*rank, unit Key 제거
~~*병사들의 반납현황을 보여주는 return key 추가 ("true", "false", "error"가 들어갈 예정입니다.)~~

위에 삭선은 #59 이슈로 생성

**Comment by riyenas0925** [comment]
@Jinwhuy 
rank, unit key삭제는 쉽게 가능한데 아래 기능은 새로운 API를 만들어야 할것 같아서요 새로운 이슈에 적어주실수 있나요?

**Comment by Jinwhuy** [comment]
넵 알겠습니다~
